<? php
echo '<html>';
echo '<head>';
echo '<title> UK Hospital </title>';
echo '';
echo '<link href="css/style.css" type="text/css" rel="stylesheet">';
echo '';
echo '</head>';
echo '<body>';
echo '';
echo '<div class="top">';
echo '<div>';
echo 'Contact Us +91 96366 20000 / 01 | ukh@hospital.com';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="logo">';
echo '<div>';
echo '<table>';
echo '<tr>';
echo '<td width="600px" style="font-size:50px;font-family:forte;"> <font color="#428bca"> UK  </font><font color="#000"> Hospital</font> </td>';
echo '<td> <br> <br>';
echo '<font size="4px">';
echo '<a href="index.php">HOME</a>';
echo '<a href="about.php">ABOUT US</a>';
echo '<a href="service.php">SERVICE</a>';
echo '<a href="doctor.php">DOCTORS</a>';
echo '<a href="contact.php">CONTACT US</a>';
echo '</font>';
echo '</td>';
echo '</tr>';
echo '</table>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '<div class="bottom">';
echo '<div>';
echo '<table border="0">';
echo '<tr>';
echo '<td width="700px">';
echo '<font color="#000">------------ </font> <br> <br>';
echo '';
echo '<font color="#000" size="6px"> Information Not available </font> <br> <br>';
echo '';
echo '';
echo '';
echo '<br>';
echo '<br>';
echo '<br>';
echo '</td>';
echo '';
echo '';
echo '<td style="padding-left:20px;"> </td>';
echo '</tr>';
echo '';
echo '';
echo '</table>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="nav_down">';
echo '<div>';
echo '&copy; UK Hospital, site designed & developed by THARE_VASTE';
echo '</div>';
echo '</div>';
echo '';
echo '';
?>
